# .cargo/config.toml
[env]
LIBTORCH = "/usr/lib/python3.14/site-packages/torch"
LD_LIBRARY_PATH = { value = "/usr/lib/python3.14/site-packages/torch/lib", relative = false }
LIBTORCH_USE_PYTORCH = "1"
CUDARC_CUDA_VERSION = "12.8"